[package]
name = "scrounch_backend"
version = "0.1.0"
edition = "2021"

# Enable high optimizations for dependencies:
[profile.dev.package."*"]
opt-level = 3

# Git hooks
[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["precommit-hook", "run-cargo-check", "run-cargo-clippy", "run-cargo-fmt"]

[dependencies]
## Rest API
axum = "0.7.5"
tower = "0.5.1"

# Runtime
tokio = { version = "1.40.0", features = ["full"] }
