[package]
name = "scrounch_backend"
version = "0.1.0"
edition = "2021"

# Git hooks
[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["precommit-hook", "run-cargo-check", "run-cargo-clippy", "run-cargo-fmt"]

[dependencies]
